"""Tests for the evidence / provenance trace endpoint (ROADMAP M7, SPEC §26)."""

from __future__ import annotations

from fastapi.testclient import TestClient

from app.evidence import run_evidence
from app.main import create_app
from app.policy.dsl import (
    Intervention,
    InterventionType,
    PolicyDSL,
    RevenueAllocation,
)

app = create_app()
client = TestClient(app)


def _policy(amount: float = 12.0, pt_share: float = 1.0) -> PolicyDSL:
    return PolicyDSL(
        id="policy_evidence_test",
        intervention=Intervention(
            type=InterventionType.road_pricing, amount=amount, currency="local"
        ),
        revenue_allocation=RevenueAllocation(
            public_transport=pt_share, general_fund=1.0 - pt_share
        ),
    )


def _body(metric_key: str, **extra: object) -> dict:
    return {"policy": _policy().model_dump(mode="json"), "metric_key": metric_key, **extra}


def test_trace_has_full_causal_ladder() -> None:
    tr = run_evidence(_policy(), "transit.peak_into_cbd_transit_trips")
    stages = [s.stage for s in tr.chain]
    # Ladder runs from raw inputs to the result.
    assert stages[0] == "input-data"
    assert stages[-1] == "result"
    assert "model" in stages
    assert any(s.stage == "transform" for s in tr.chain)
    # Result node carries the isolated Δ.
    result_step = tr.chain[-1]
    assert result_step.value == tr.result.delta


def test_endpoint_contract() -> None:
    r = client.post("/evidence", json=_body("traffic.vehicle_trips_into_cbd"))
    assert r.status_code == 200, r.text
    data = r.json()
    assert data["metric_key"] == "traffic.vehicle_trips_into_cbd"
    assert data["provenance"] == "Simulated"
    assert data["ascii_trace"].strip()
    assert "↓" in data["ascii_trace"]
    assert data["rules"], "should surface the behavioural levers behind the number"
    assert data["citations"]
    assert data["historical_analogues"]


def test_unknown_metric_is_404_with_available_keys() -> None:
    r = client.post("/evidence", json=_body("nope.not_a_metric"))
    assert r.status_code == 404
    detail = r.json()["detail"]
    assert "available_metric_keys" in detail
    assert "traffic.vehicle_trips_into_cbd" in detail["available_metric_keys"]


def test_confidence_falls_with_horizon() -> None:
    early = run_evidence(_policy(), "traffic.daily_vehicle_km", horizon_months=1)
    late = run_evidence(_policy(), "traffic.daily_vehicle_km", horizon_months=120)
    assert late.confidence.value < early.confidence.value
    # Horizon snapping lands on the requested checkpoint.
    assert early.horizon.t_months == 1.0
    assert late.horizon.t_months == 120.0


def test_reinvestment_lever_only_traces_into_transit_metrics() -> None:
    # Transit metric: both charge and reinvestment levers are relevant.
    transit = run_evidence(_policy(pt_share=1.0), "transit.peak_into_cbd_transit_trips")
    names = {r.name for r in transit.rules}
    assert "transit_reinvestment" in names
    assert "cordon_charge" in names
    # Pure traffic metric: reinvestment has no path to it.
    traffic = run_evidence(_policy(pt_share=1.0), "traffic.daily_vehicle_km")
    assert "transit_reinvestment" not in {r.name for r in traffic.rules}
    assert "cordon_charge" in {r.name for r in traffic.rules}


def test_no_generated_numbers_all_simulated_or_reference() -> None:
    tr = run_evidence(_policy(), "emissions.daily_co2_tonnes")
    # Every chain node is Simulated (numbers) — none Generated by an LLM.
    for step in tr.chain:
        assert step.tag.value != "Generated"
    # Analogues are external Observed reference facts, clearly flagged.
    for a in tr.historical_analogues:
        assert a.tag.value == "Observed"
        assert "not a source" in a.note


def test_deterministic() -> None:
    a = run_evidence(_policy(), "mode_share.car_pct").model_dump()
    b = run_evidence(_policy(), "mode_share.car_pct").model_dump()
    assert a == b
